openapi: 3.0.0
info:
  title: WORDS-FREQUENCY-EVALUATOR
  version: 1.0.0
  description: Service for adding words and getting statistics on them

paths:
  /api/words:
    get:
      tags:
        - Word
      operationId: getWords
      summary: Provides words frequency statistic. Top 5 recurring words, Minimum frequency among all words, The median frequency
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Words'
        'default':
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Word
      operationId: addWords
      summary: Adds words in storage. Accept a string of comma-separated words
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              description: A string of comma-separated words
              example: ball,eggs,pool,dart,ball,ball
      responses:
        '201':
          description: OK
        'default':
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Words:
      type: string
    Error:
      type: object
      properties:
        errorCode:
          type: string
          description: Internal error code. Filled if status <> 2xx
          example: WFE-100
        errorMessage:
          type: string
          description: Error description. Filled if status <> 2xx
          example: Error description
        traceId:
          type: string
          description: Trace ID. Filled if status <> 2xx
          example: ed7a9f7d-466c-433e-9ad4-3900dc936d19