micronaut:
    server.port: 8080
    application:
        name: WordsFrequencyEvaluator
    security:
        enabled: false
    metrics:
        enabled: true
        export:
            prometheus:
                enabled: true
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
            swagger-ui:
                paths: classpath:META-INF/swagger/views/swagger-ui
                mapping: /swagger-ui/**

endpoints:
    all:
        enabled: false
        sensitive: false
        port: 8084
    metrics:
        enabled: true
    prometheus:
        enabled: true

server:
    filter:
        path: /**
